namespaces:
  - name: everest
    operators:
      - pxc
      - psmdb
      - pg
  - name: psmdb-only
    operators:
      - psmdb
  - name: pxc-only
    operators:
      - pxc
  - name: pg-only
    operators:
      - pg
