name: API Docs

on:
  workflow_dispatch:

jobs:
  rdme-openapi:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo ðŸ“š
        uses: actions/checkout@v6

      - name: Run `openapi` command ðŸš€
        uses: readmeio/rdme@v10
        with:
          rdme: openapi upload ./docs/spec/openapi.yml --key=${{ secrets.README_API_KEY }}
