---
name: EVEREST-1023-test-flow
on:
  push:
    branches: [EVEREST-1023]

permissions:
  contents: read
  packages: write
  checks: write
  pull-requests: write
  repository-projects: read

jobs:
  test_run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run the main workflow from PR branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch origin EVEREST-1023
          git checkout FETCH_HEAD
          github.actions.getWorkflowAccess()
          ./.github/workflows/dev-fe-ci.yaml