---
name: Release helmtools Docker image
on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version tag for the image"
        required: true
      kubectl_version:
        description: "Version of kubectl to use"
        required: false
        default: "v1.33.5"
jobs:
  release:
     env:
      IMG_OWNER: percona
      IMG_NAME: everest-helmtools
      VERSION: ${{ github.event.inputs.version }}
      KUBECTL_VERSION: ${{ github.event.inputs.kubectl_version }}

     runs-on: ubuntu-latest
     steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          repository: percona/everest
          path: everest
          token: ${{ secrets.ROBOT_TOKEN }}
          sparse-checkout: |
            Dockerfile.helmtools

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        name: Build & push Docker image
        with:
          context: everest
          push: true
          tags: ${{ env.IMG_OWNER }}/${{ env.IMG_NAME }}:${{ env.VERSION }}
          file: everest/Dockerfile.helmtools
          build-args: |
            KUBECTL_VERSION=${{ env.KUBECTL_VERSION }}
